### ISSUE TITLE
[VIPM] Missing dep: "JDP Common Science Utilities"

### ISSUE THREAD

**Issue by jackparmer** [nominal-io/labview-client#8]
This error appears after installing Nominal in VIPM.

Windows version: "Windows 11 Home"
LabVIEW edition: Community 2022 Q3

I was unable to install the missing JDP Common Science Utilities" package manually (VIPM error screenshot below).

In LabVIEW, the Nominal VIs do not show under Data Communications unless searched. If a VI is clicked, it crashes the control panel with an error related to the missing "JDP Common Science Utilities" dep.

## JDP missing dep error within VIPM

<img width="577" alt="image" src="https://github.com/user-attachments/assets/1cfd2269-17bc-4a5b-b300-e26092d9411f">

<img width="696" alt="image" src="https://github.com/user-attachments/assets/e0f9230e-291f-4dcc-ab79-eada4bbea41a">

## LabVIEW version

<img width="983" alt="image" src="https://github.com/user-attachments/assets/314d1fb8-a501-4534-9af0-9087ba7eada9">

## Windows version

<img width="937" alt="image" src="https://github.com/user-attachments/assets/494ffc75-2c30-4f70-a3a7-e4f5ddfeac17">

## JDP missing dep error within LabVIEW

<img width="879" alt="image" src="https://github.com/user-attachments/assets/80028b73-6d53-4f00-9c2d-9458c56327bc">

**Comment by Tom-McQuillan** [comment]
My first thought was that the dep wasn't declared. But it is... 
JDP Science Common Utilities v1.4.1.18 already exists in the dependency list
![image](https://github.com/user-attachments/assets/43e7992c-5689-4cac-b500-a48761952935)

**Comment by Tom-McQuillan** [comment]
I've been able to reproduce the issue on a completely fresh VM.
![image](https://github.com/user-attachments/assets/4d9de4d6-eaba-43f6-95ab-da31eddb3151)
